title: Giulia Benintendi
description: Human-centered AI & Robotics
url: "https://giuliabenintendi.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag

author:
  name: Giulia Benintendi
  email: giulbenintendi@gmail.com

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CV_GiuliaBenintendi.pdf
  - CV_GiuliaBenintendi_Oct2025.pdf
